// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: media.proto

package mediapb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MediaClient is the client API for Media service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaClient interface {
	CreateMedia(ctx context.Context, opts ...grpc.CallOption) (Media_CreateMediaClient, error)
	DeleteMedia(ctx context.Context, in *DeleteMediaRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type mediaClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaClient(cc grpc.ClientConnInterface) MediaClient {
	return &mediaClient{cc}
}

func (c *mediaClient) CreateMedia(ctx context.Context, opts ...grpc.CallOption) (Media_CreateMediaClient, error) {
	stream, err := c.cc.NewStream(ctx, &Media_ServiceDesc.Streams[0], "/Media/CreateMedia", opts...)
	if err != nil {
		return nil, err
	}
	x := &mediaCreateMediaClient{stream}
	return x, nil
}

type Media_CreateMediaClient interface {
	Send(*MediaCreateRequest) error
	CloseAndRecv() (*MediaCreateResponse, error)
	grpc.ClientStream
}

type mediaCreateMediaClient struct {
	grpc.ClientStream
}

func (x *mediaCreateMediaClient) Send(m *MediaCreateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mediaCreateMediaClient) CloseAndRecv() (*MediaCreateResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MediaCreateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mediaClient) DeleteMedia(ctx context.Context, in *DeleteMediaRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Media/DeleteMedia", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServer is the server API for Media service.
// All implementations must embed UnimplementedMediaServer
// for forward compatibility
type MediaServer interface {
	CreateMedia(Media_CreateMediaServer) error
	DeleteMedia(context.Context, *DeleteMediaRequest) (*empty.Empty, error)
	mustEmbedUnimplementedMediaServer()
}

// UnimplementedMediaServer must be embedded to have forward compatible implementations.
type UnimplementedMediaServer struct {
}

func (UnimplementedMediaServer) CreateMedia(Media_CreateMediaServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateMedia not implemented")
}
func (UnimplementedMediaServer) DeleteMedia(context.Context, *DeleteMediaRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMedia not implemented")
}
func (UnimplementedMediaServer) mustEmbedUnimplementedMediaServer() {}

// UnsafeMediaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServer will
// result in compilation errors.
type UnsafeMediaServer interface {
	mustEmbedUnimplementedMediaServer()
}

func RegisterMediaServer(s grpc.ServiceRegistrar, srv MediaServer) {
	s.RegisterService(&Media_ServiceDesc, srv)
}

func _Media_CreateMedia_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaServer).CreateMedia(&mediaCreateMediaServer{stream})
}

type Media_CreateMediaServer interface {
	SendAndClose(*MediaCreateResponse) error
	Recv() (*MediaCreateRequest, error)
	grpc.ServerStream
}

type mediaCreateMediaServer struct {
	grpc.ServerStream
}

func (x *mediaCreateMediaServer) SendAndClose(m *MediaCreateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mediaCreateMediaServer) Recv() (*MediaCreateRequest, error) {
	m := new(MediaCreateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Media_DeleteMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServer).DeleteMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Media/DeleteMedia",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServer).DeleteMedia(ctx, req.(*DeleteMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Media_ServiceDesc is the grpc.ServiceDesc for Media service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Media_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Media",
	HandlerType: (*MediaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteMedia",
			Handler:    _Media_DeleteMedia_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateMedia",
			Handler:       _Media_CreateMedia_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "media.proto",
}
